# Generated by Django 5.1.6 on 2025-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='desc',
        ),
        migrations.AlterField(
            model_name='manga',
            name='pic',
            field=models.ImageField(null=True, upload_to='mangas/'),
        ),
    ]
