# Generated by Django 5.1.6 on 2025-02-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_manga_desc_alter_manga_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='desc',
            field=models.TextField(default=None),
        ),
    ]
