# Generated by Django 5.1.6 on 2025-03-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='donationdetails',
            old_name='Amount',
            new_name='amount',
        ),
    ]
